apiVersion: v1
entries:
  k3s-alert:
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T13:55:00.962083+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: 950a69ea330c412072b8ef4ca453ec8d7de23fabbbc89f3bdaf916cc4ab498b7
    name: k3s-alert
    type: application
    urls:
    - https://ashwinijindal10.github.io/k3s-alert-helm-repo/charts/k3s-alert-0.3.0.tgz
    version: 0.3.0
generated: "2026-04-16T13:55:00.960003+05:30"
