apiVersion: v1
entries:
  k3s-alert:
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T18:56:17.497598+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: ce2e4911431420b673ad4a6f04dd471dcf4ae5183b19e284731b0ea0513c7ba6
    name: k3s-alert
    type: application
    urls:
    - https://ashwinijindal10.github.io/k3s-alert-helm-repo/charts/k3s-alert-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T18:56:17.497216+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: ae318033025d3d9d9ced32600084fa22b4c784c0aeb167c02ef7c60c51a0e2a5
    name: k3s-alert
    type: application
    urls:
    - https://ashwinijindal10.github.io/k3s-alert-helm-repo/charts/k3s-alert-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T16:25:42.86523+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: 8407f7fda1882f30ebca5aaf17f6059bf91408fdb8906b55241c7d9de273180f
    name: k3s-alert
    type: application
    urls:
    - https://ashwinijindal10.github.io/k3s-alert-helm-repo/charts/k3s-alert-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T16:25:42.861073+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: 3819c98ae43fc303d453dabc03280af1b1cfe63d2cf2784ab23eb3be2616d5c5
    name: k3s-alert
    type: application
    urls:
    - https://ashwinijindal10.github.io/k3s-alert-helm-repo/charts/k3s-alert-0.3.1.tgz
    version: 0.3.1
generated: "2026-04-16T18:56:17.491142+05:30"
