apiVersion: v1
entries:
  k3s-alert:
  - apiVersion: v2
    appVersion: "3.0"
    created: "2026-04-16T12:42:22.416975+05:30"
    description: Lightweight optimized Kubernetes alert cronjob
    digest: 53944b461a061356c907899ee6cc88b799ce95e547be33a5e651b8b0a4e62746
    name: k3s-alert
    type: application
    urls:
    - https://raw.githubusercontent.com/ashwinijindal10/k3s-alert-helm-repo/main/docs/charts/k3s-alert-0.3.0.tgz
    version: 0.3.0
generated: "2026-04-16T12:42:22.414531+05:30"
